version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 200322876  
      POSTGRES_DB: testdb
      POSTGRES_USER: root     

